<a href="https://colab.research.google.com/github/dimages/hw/blob/main/Raifhack2_0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
import pandas as pd

file_path = '/content/drive/MyDrive/train.csv'
df = pd.read_csv(file_path)

<ipython-input-3-db0319147120>:4: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)

In [4]:
df.head(10)

,city,floor,id,lat,lng,osm_amenity_points_in_0.001,osm_amenity_points_in_0.005,osm_amenity_points_in_0.0075,osm_amenity_points_in_0.01,osm_building_points_in_0.001,...,reform_mean_floor_count_1000,reform_mean_floor_count_500,reform_mean_year_building_1000,reform_mean_year_building_500,region,total_square,street,date,realty_type,price_type
0,Пермь,NaN,COL_0,57.998207,56.292797,4,19,35,52,0,...,5.762963,5.530612,1964.118519,1960.959184,Пермский край,32.0,S27289,2020-01-05,10,0
1,Шатура,NaN,COL_1,55.574284,39.543835,3,24,37,59,0,...,2.894366,3.527778,1952.321678,1957.222222,Московская область,280.0,S17052,2020-01-05,10,0
2,Ярославль,NaN,COL_2,57.619140,39.850525,1,30,67,128,0,...,6.141414,7.222222,1968.150000,1973.370370,Ярославская область,297.4,S16913,2020-01-05,110,0
3,Новокузнецк,NaN,COL_3,53.897083,87.108604,0,0,5,21,0,...,8.581081,9.000000,1992.716216,2014.000000,Кемеровская область,190.0,S10148,2020-01-05,110,0
4,Москва,NaN,COL_4,55.802590,37.487110,1,23,64,153,0,...,7.263889,5.684211,1963.229167,1960.500000,Москва,60.2,S1338,2020-01-05,10,0
5,Самара,NaN,COL_5,53.257900,50.203632,0,18,38,50,0,...,11.644737,15.823529,1875.819277,1550.818182,Самарская область,308.0,S24380,2020-01-05,100,0
6,Лаишево,NaN,COL_6,55.412357,49.561718,0,0,0,0,0,...,2.500000,2.750000,2005.500000,2013.750000,Татарстан,130.0,S14468,2020-01-05,10,0
7,Саратов,NaN,COL_7,51.521416,46.016453,0,38,117,219,0,...,6.118012,5.934783,1961.305882,1961.312500,Саратовская область,291.0,S8394,2020-01-05,10,0
8,Краснодар,NaN,COL_8,45.033280,38.976410,3,92,256,376,0,...,1.857407,1.724359,1925.483456,1921.840764,Краснодарский край,680.0,S33225,2020-01-05,100,0
9,Екатеринбург,NaN,COL_9,56.833660,60.635742,5,66,138,249,0,...,5.925676,6.125000,1967.295302,1966.200000,Свердловская область,28.0,S5897,2020-01-05,100,0

In [5]:
df.shape

(279792, 77)

In [6]:
df.isna().any().any()

True